<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="../test.props" />

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.HttpOverrides" Version="2.3.11" />
        <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
        <PackageReference Update="SimpleInjector.Integration.AspNetCore.Mvc.Core" Version="5.5.0" />
        <PackageReference Include="System.Composition.AttributedModel" Version="10.0.9" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="10.0.9" />
    </ItemGroup>

</Project>
